name: Sherlock
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4458374616224319
title: 'A Visual Collection '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9734151612501591
  lightness: 0.175221330486238
  saturation: 0.587492678547278
  rhythmicContrast: 0.3369401949457824
purpose: []
